// ════════════════════════════════════════════════════════════════
// EOT HQ — Master Script v1.0
// Paste into: Master Sheet → Extensions → Apps Script
// Deploy as Web App: Execute as Me, Access: Anyone
// This single deployment serves ALL customer pages.
// ════════════════════════════════════════════════════════════════

// ── SCRIPT PROPERTIES (set via Project Settings → Script Properties)
// TEMPLATE_SHEET_ID  — ID of the Customer Template Sheet you created
// VERCEL_URL         — e.g. https://easyordertracking.vercel.app
// REVALIDATE_SECRET  — same random string as in Vercel env vars
// DASHBOARD_SECRET   — auto-generated by setup()

// ─────────────────────────────────────────────────────────────────
// MENU
// ─────────────────────────────────────────────────────────────────
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('🚀 EasyOrderTracking HQ')
    .addItem('📋 Create New Website', 'createWebsite')
    .addItem('📊 Refresh Dashboard',  'refreshDashboard')
    .addSeparator()
    .addItem('💾 Run Backup',         'runBackup')
    .addItem('🔧 Setup (Run Once)',   'setup')
    .addToUi();
}

// ─────────────────────────────────────────────────────────────────
// doGet — THE SINGLE PUBLIC ENDPOINT
// All website traffic routes through here.
// ─────────────────────────────────────────────────────────────────
function doGet(e) {
  var params = e.parameter || {};
  var action = String(params.action || 'resolve');
  var code   = String(params.code   || '').trim();

  // ── Dashboard (protected, your eyes only) ──
  if (action === 'dashboard') {
    var secret = prop_('DASHBOARD_SECRET');
    if (params.secret !== secret) return jsonOut_({ error: 'unauthorized' });
    return jsonOut_(getDashboardData_());
  }

  if (!code) return jsonOut_({ error: 'missing code' });

  // ── Look up code ──
  var codeRow = findCode_(code);
  if (!codeRow) return jsonOut_({ found: false, error: 'code not found' });

  try {
    var cs = SpreadsheetApp.openById(codeRow.sheetId);

    if (action === 'resolve') return jsonOut_(resolveConfig_(cs, code));
    if (action === 'orders')  return jsonOut_(getOrders_(cs));

    return jsonOut_({ error: 'unknown action' });
  } catch (err) {
    log_('ERROR', 'doGet[' + action + '/' + code + ']: ' + err.message);
    return jsonOut_({ error: err.message });
  }
}

// ─────────────────────────────────────────────────────────────────
// findCode_ — looks up Codes sheet → returns { sheetId, status }
// ─────────────────────────────────────────────────────────────────
function findCode_(code) {
  var sheet = ss_().getSheetByName('Codes');
  if (!sheet) return null;
  var data = sheet.getDataRange().getValues();
  // Columns: Code | Sheet ID | Script URL (unused) | Status | Created At
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][0]) === code && String(data[i][3]) === 'Active') {
      return { code: data[i][0], sheetId: String(data[i][1]) };
    }
  }
  return null;
}

// ─────────────────────────────────────────────────────────────────
// resolveConfig_ — returns brand config from customer sheet's admin + _config tabs
// Called by Next.js getStaticProps (ISR, cached 5 min)
// ─────────────────────────────────────────────────────────────────
function resolveConfig_(cs, code) {
  var admin  = kvRead_(cs, 'admin');
  var config = kvRead_(cs, '_config');

  return {
    found:      true,
    code:       code,
    brandName:  admin['brand_name']       || config['brand_name'] || '',
    tagline:    admin['tagline']          || 'Live Order Status',
    showSearch: admin['show_search']      !== 'no',
    bottomBar: {
      mode:   admin['bottombar_mode']    || 'notification',
      text:   admin['bottombar_text']    || '',
      link:   admin['bottombar_link']    || '',
      active: admin['bottombar_active']  !== 'no',
    },
  };
}

// ─────────────────────────────────────────────────────────────────
// getOrders_ — reads daily_tracking, filters, returns orders array
// Called by /api/orders (cached 28s at Vercel CDN)
// ─────────────────────────────────────────────────────────────────
function getOrders_(cs) {
  var sheet = cs.getSheetByName('daily_tracking');
  if (!sheet) return { orders: [], count: 0 };

  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return { orders: [], count: 0 };

  var headers = data[0].map(function(h) { return String(h).trim(); });
  var now     = new Date();
  var cutoff  = new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000); // 10 days ago
  var orders  = [];

  // Read by column header name — immune to column reordering
  function ci(name) { return headers.indexOf(name); }

  for (var i = 1; i < data.length; i++) {
    var row  = data[i];
    var name = String(row[ci('Customer Name')] || '').trim();
    if (!name) continue;

    var orderId      = String(row[ci('Order ID')]        || '').trim();
    var pincode      = String(row[ci('Pincode')]         || '').trim();
    var trackingId   = String(row[ci('Tracking ID')]     || '').trim();
    var shippedOnRaw = row[ci('Shipped On')]             || '';
    var status       = String(row[ci('Delivery Status')] || 'Transit').trim();
    var trackingLink = String(row[ci('Tracking Link')]   || '').trim();

    // ── Filtering logic ──
    // Hide delivered orders that are older than 10 days (configurable via cutoff above)
    // Transit orders are always shown — they need attention
    if (status === 'Delivered' && shippedOnRaw) {
      var d = new Date(shippedOnRaw);
      if (!isNaN(d) && d < cutoff) continue;
    }

    // Format shipped date
    var shippedStr = '';
    var isNew      = false;
    if (shippedOnRaw) {
      try {
        var sd = new Date(shippedOnRaw);
        if (!isNaN(sd)) {
          shippedStr = sd.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
          isNew = (now - sd) < 24 * 60 * 60 * 1000;
        }
      } catch (_) {}
    }

    orders.push({
      orderId:      orderId,
      name:         name,
      pincode:      pincode,
      trackingId:   trackingId,
      status:       status,
      trackingLink: trackingLink,
      shippedOn:    shippedStr,
      isNew:        isNew,
    });
  }

  orders.reverse(); // newest first
  return { orders: orders, count: orders.length, ts: now.getTime() };
}

// ─────────────────────────────────────────────────────────────────
// createWebsite — clones template, assigns code, wires everything up
// ─────────────────────────────────────────────────────────────────
function createWebsite() {
  var ui = SpreadsheetApp.getUi();

  // ── Find pending row ──
  var src     = ss_().getSheetByName('Create New Website');
  if (!src) { ui.alert('Sheet "Create New Website" not found. Run Setup first.'); return; }

  var data    = src.getDataRange().getValues();
  var headers = data[0];
  function hi(name) { return headers.indexOf(name); }

  var targetRow = -1;
  for (var i = 1; i < data.length; i++) {
    var biz  = String(data[i][hi('Business Name')] || '').trim();
    var code = String(data[i][hi('Code')]          || '').trim();
    if (biz && !code) { targetRow = i; break; }
  }

  if (targetRow === -1) {
    ui.alert('No pending row found.\nFill a Business Name row in "Create New Website" first.');
    return;
  }

  var row       = data[targetRow];
  var bizName   = String(row[hi('Business Name')] || '').trim();
  var ownerName = String(row[hi('Owner Name')]    || '').trim();
  var ownerPh   = String(row[hi('Owner Phone')]   || '').trim();
  var pocName   = String(row[hi('POC Name')]      || '').trim();
  var pocPh     = String(row[hi('POC Phone')]     || '').trim();
  var csmEmail  = String(row[hi('CSM Email')]     || '').trim();
  var notes     = String(row[hi('Notes')]         || '').trim();

  if (!bizName) { ui.alert('Business Name is required.'); return; }

  // ── Get template ID ──
  var TEMPLATE_ID = prop_('TEMPLATE_SHEET_ID');
  if (!TEMPLATE_ID) {
    ui.alert('TEMPLATE_SHEET_ID not set.\nGo to Extensions → Apps Script → Project Settings → Script Properties and add it.');
    return;
  }

  var VERCEL_URL = prop_('VERCEL_URL') || 'https://easyordertracking.vercel.app';

  // ── Generate unique 6-digit code ──
  var code_ = generateCode_();

  // ── Clone template ──
  var templateFile = DriveApp.getFileById(TEMPLATE_ID);
  var newFile      = templateFile.makeCopy(bizName + ' — EasyOrderTracking');
  var newSheetId   = newFile.getId();

  // ── Configure new sheet ──
  var newSs   = SpreadsheetApp.openById(newSheetId);
  var prefix  = bizName.replace(/[^a-zA-Z]/g, '').toUpperCase().slice(0, 3) || 'ORD';
  var secret  = prop_('REVALIDATE_SECRET') || '';

  kvWrite_(newSs, '_config', {
    customer_code:      code_,
    brand_name:         bizName,
    brand_prefix:       prefix,
    created_at:         new Date().toISOString(),
    schema_version:     '1.0',
    tracking_provider:  'speedposttrack',
    tracking_base_url:  '',
    vercel_url:         VERCEL_URL,
    revalidate_secret:  secret,
  });

  kvWrite_(newSs, 'admin', {
    brand_name:       bizName,
    tagline:          'Live Order Status',
    bottombar_mode:   'notification',
    bottombar_text:   '',
    bottombar_link:   '',
    bottombar_active: 'yes',
    show_search:      'yes',
  });

  // ── Add CSM as editor ──
  if (csmEmail) {
    try { newSs.addEditor(csmEmail); } catch (_) {}
  }

  var trackingUrl = VERCEL_URL + '/' + code_;
  var sheetUrl    = 'https://docs.google.com/spreadsheets/d/' + newSheetId;
  var rowNum      = targetRow + 1; // 1-indexed

  // ── Update source row ──
  src.getRange(rowNum, hi('Code')       + 1).setValue(code_);
  src.getRange(rowNum, hi('Sheet URL')  + 1).setValue(sheetUrl);
  src.getRange(rowNum, hi('Status')     + 1).setValue('Active');
  src.getRange(rowNum, hi('Created At') + 1).setValue(new Date());

  // ── Append to Live Websites ──
  var live = ss_().getSheetByName('Live Websites');
  if (live) {
    live.appendRow([
      code_, bizName, ownerName, ownerPh, pocName, pocPh,
      csmEmail, sheetUrl, 'Active', new Date(), '', notes
    ]);
  }

  // ── Append to Codes (lookup table) ──
  var codes = ss_().getSheetByName('Codes');
  if (codes) codes.appendRow([code_, newSheetId, '', 'Active', new Date()]);

  log_('INFO', 'Created: ' + bizName + ' → code:' + code_);

  ui.alert(
    '✅ Website Created!\n\n' +
    'Business : ' + bizName    + '\n' +
    'Code     : ' + code_      + '\n' +
    'URL      : ' + trackingUrl + '\n\n' +
    'Sheet    : ' + sheetUrl
  );
}

// ─────────────────────────────────────────────────────────────────
// generateCode_ — 6 digits, first and last not 0
// ─────────────────────────────────────────────────────────────────
function generateCode_() {
  for (var attempt = 0; attempt < 200; attempt++) {
    var d = [];
    d.push(String(Math.floor(Math.random() * 9) + 1)); // 1-9
    for (var i = 0; i < 4; i++) d.push(String(Math.floor(Math.random() * 10))); // 0-9
    d.push(String(Math.floor(Math.random() * 9) + 1)); // 1-9
    var code = d.join('');
    if (isCodeUnique_(code)) return code;
  }
  throw new Error('Could not generate a unique code. Check Codes sheet.');
}

function isCodeUnique_(code) {
  var sheet = ss_().getSheetByName('Codes');
  if (!sheet) return true;
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][0]) === code) return false;
  }
  return true;
}

// ─────────────────────────────────────────────────────────────────
// churnWebsite — marks a business as churned, website returns 404
// Call manually from menu after removing them from Live Websites
// ─────────────────────────────────────────────────────────────────
function churnWebsite() {
  var ui   = SpreadsheetApp.getUi();
  var resp = ui.prompt('Enter the 6-digit code of the business to churn:');
  if (resp.getSelectedButton() !== ui.Button.OK) return;

  var code  = resp.getResponseText().trim();
  var sheet = ss_().getSheetByName('Codes');
  if (!sheet) { ui.alert('Codes sheet not found.'); return; }

  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][0]) === code) {
      sheet.getRange(i + 1, 4).setValue('Churned'); // Status column
      log_('INFO', 'Churned: ' + code);
      ui.alert('✅ Code ' + code + ' is now churned. The tracking page will show 404.');
      return;
    }
  }
  ui.alert('Code ' + code + ' not found in Codes sheet.');
}

// ─────────────────────────────────────────────────────────────────
// getDashboardData_ — aggregate stats for dashboard
// ─────────────────────────────────────────────────────────────────
function getDashboardData_() {
  var live = ss_().getSheetByName('Live Websites');
  if (!live) return {};

  var data    = live.getDataRange().getValues();
  var headers = data[0];
  function hi(n) { return headers.indexOf(n); }

  var active = 0, churned = 0;
  for (var i = 1; i < data.length; i++) {
    var st = String(data[i][hi('Status')] || '');
    if (st === 'Active')  active++;
    if (st === 'Churned') churned++;
  }

  return {
    activeCustomers:  active,
    churnedCustomers: churned,
    totalCustomers:   active + churned,
    ts:               new Date().getTime(),
  };
}

// ─────────────────────────────────────────────────────────────────
// refreshDashboard — updates Dashboard sheet with aggregate stats
// Also runs daily via time-based trigger (set up in Triggers panel)
// ─────────────────────────────────────────────────────────────────
function refreshDashboard() {
  var stats = getDashboardData_();
  var dash  = ss_().getSheetByName('Dashboard');
  if (!dash) return;

  dash.clearContents();
  dash.getRange('A1').setValue('EasyOrderTracking — HQ Dashboard');
  dash.getRange('A1').setFontWeight('bold').setFontSize(14);
  dash.getRange('A3').setValue('Last Updated');
  dash.getRange('B3').setValue(new Date());
  dash.getRange('A4').setValue('Active Customers');
  dash.getRange('B4').setValue(stats.activeCustomers);
  dash.getRange('A5').setValue('Churned Customers');
  dash.getRange('B5').setValue(stats.churnedCustomers);
  dash.getRange('A6').setValue('Total Ever');
  dash.getRange('B6').setValue(stats.totalCustomers);
}

// ─────────────────────────────────────────────────────────────────
// runBackup — saves JSON snapshot of Codes + Live Websites to Drive
// Also runs nightly via time-based trigger
// ─────────────────────────────────────────────────────────────────
function runBackup() {
  var backup = { ts: new Date().toISOString() };

  var codes = ss_().getSheetByName('Codes');
  if (codes) backup.codes = codes.getDataRange().getValues();

  var live = ss_().getSheetByName('Live Websites');
  if (live) backup.live = live.getDataRange().getValues();

  var folderIt = DriveApp.getFoldersByName('EOT_Backups');
  var folder   = folderIt.hasNext() ? folderIt.next() : DriveApp.createFolder('EOT_Backups');

  var fname = 'EOT_Backup_' + Utilities.formatDate(new Date(), 'Asia/Kolkata', 'yyyyMMdd_HHmm') + '.json';
  folder.createFile(fname, JSON.stringify(backup, null, 2), 'application/json');

  log_('INFO', 'Backup saved: ' + fname);
}

// ─────────────────────────────────────────────────────────────────
// setup — creates all sheets, sets up headers, generates secrets
// ─────────────────────────────────────────────────────────────────
function setup() {
  var ui = SpreadsheetApp.getUi();

  function ensureSheet(name, headers, bg) {
    var sh = ss_().getSheetByName(name) || ss_().insertSheet(name);
    if (headers && sh.getLastRow() === 0) {
      var r = sh.getRange(1, 1, 1, headers.length);
      r.setValues([headers]);
      r.setFontWeight('bold').setBackground(bg || '#1a1a2e').setFontColor('#ffffff');
      sh.setFrozenRows(1);
    }
    return sh;
  }

  ensureSheet('Create New Website', [
    'Business Name','Owner Name','Owner Phone','POC Name','POC Phone',
    'CSM Email','Notes','Status','Code','Sheet URL','Created At'
  ]);

  ensureSheet('Live Websites', [
    'Code','Business Name','Owner Name','Owner Phone','POC Name','POC Phone',
    'CSM Email','Sheet URL','Status','Created At','Churned At','Notes'
  ]);

  ensureSheet('Dashboard', [], '#1a1a2e');
  ensureSheet('Codes',     ['Code','Sheet ID','Script URL','Status','Created At'], '#111111').hideSheet();
  ensureSheet('Log',       ['Timestamp','Level','Message'], '#111111').hideSheet();

  // Generate dashboard secret
  if (!prop_('DASHBOARD_SECRET')) {
    PropertiesService.getScriptProperties().setProperty('DASHBOARD_SECRET', Utilities.getUuid());
  }

  // Set up daily backup trigger if not already present
  var triggers = ScriptApp.getProjectTriggers();
  var hasBackup = triggers.some(function(t) { return t.getHandlerFunction() === 'runBackup'; });
  if (!hasBackup) {
    ScriptApp.newTrigger('runBackup').timeBased().everyDays(1).atHour(2).create();
  }

  var hasRefresh = triggers.some(function(t) { return t.getHandlerFunction() === 'refreshDashboard'; });
  if (!hasRefresh) {
    ScriptApp.newTrigger('refreshDashboard').timeBased().everyHours(6).create();
  }

  ui.alert(
    '✅ HQ Setup complete!\n\n' +
    'Next steps:\n' +
    '1. Create Customer Template Sheet (see SETUP_GUIDE.md)\n' +
    '2. Script Properties → Add:\n' +
    '   TEMPLATE_SHEET_ID = <id of template sheet>\n' +
    '   VERCEL_URL        = https://easyordertracking.vercel.app\n' +
    '   REVALIDATE_SECRET = <same as Vercel env var>\n' +
    '3. Deploy → New Deployment → Web App\n' +
    '   Execute as: Me | Access: Anyone\n' +
    '4. Copy Web App URL → add as HQ_ENDPOINT in Vercel'
  );
}

// ─────────────────────────────────────────────────────────────────
// KV helpers — key-value tabs (2 columns: key | value)
// ─────────────────────────────────────────────────────────────────
function kvRead_(ss, sheetName) {
  var sh = ss.getSheetByName(sheetName);
  if (!sh) return {};
  var result = {};
  sh.getDataRange().getValues().forEach(function(row) {
    if (row[0]) result[String(row[0]).trim()] = row[1];
  });
  return result;
}

function kvWrite_(ss, sheetName, obj) {
  var sh = ss.getSheetByName(sheetName) || ss.insertSheet(sheetName);
  sh.clearContents();
  var rows = Object.keys(obj).map(function(k) { return [k, obj[k]]; });
  if (rows.length) sh.getRange(1, 1, rows.length, 2).setValues(rows);
}

// ─────────────────────────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────────────────────────
function ss_()          { return SpreadsheetApp.getActiveSpreadsheet(); }
function prop_(key)     { return PropertiesService.getScriptProperties().getProperty(key) || ''; }
function jsonOut_(obj)  { return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON); }

function log_(level, msg) {
  try {
    var log = ss_().getSheetByName('Log') || ss_().insertSheet('Log');
    log.appendRow([new Date(), level, msg]);
  } catch (_) {}
}
